"""add expired field to tracking links

Revision ID: 6e7195efb02c
Revises: f50c865b33d8
Create Date: 2025-04-20 22:27:38.903997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7195efb02c'
down_revision = 'f50c865b33d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracking_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_expired', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracking_link', schema=None) as batch_op:
        batch_op.drop_column('is_expired')

    # ### end Alembic commands ###
