"""add short_id to tracking links

Revision ID: cce9c8b064c9
Revises: 6e7195efb02c
Create Date: 2025-04-20 23:27:48.850437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cce9c8b064c9'
down_revision = '6e7195efb02c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracking_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_id', sa.String(length=4), nullable=True))
        batch_op.create_unique_constraint(None, ['short_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracking_link', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('short_id')

    # ### end Alembic commands ###
